In [3]:
# !pip install numpy

In [2]:
import numpy as np

In [4]:
a = [[1, 2, 3], [1, 2, 3]]

In [13]:
a = np.array([1, 2, 3, 4, 5])

In [14]:
a.shape

(5,)

In [15]:
b = np.array([[1], 
              [2], 
              [3], 
              [4], 
              [5]])

In [16]:
b.shape

(5, 1)

In [20]:
zero = np.zeros((3, 3), dtype = 'int')

In [21]:
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
zeros = np.zeros_like(zero)

In [24]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
np.full((2, 5), 4.25)

array([[4.25, 4.25, 4.25, 4.25, 4.25],
       [4.25, 4.25, 4.25, 4.25, 4.25]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
ran_init = np.random.random((3, 3))

In [32]:
ran_init

array([[0.54556267, 0.79111574, 0.78300689],
       [0.85292096, 0.16794099, 0.64270445],
       [0.16210384, 0.4948175 , 0.79552279]])

In [36]:
np.random.randint(0, 100, (3, 3))

array([[85, 45, 47],
       [38, 68,  0],
       [33, 41, 28]])

In [38]:
np.random.randn(3, 3)

array([[-0.07292586,  1.69391703, -0.57051832],
       [ 0.06909233, -0.60607062, -0.69044078],
       [ 0.2296109 , -0.32484838,  0.34928475]])

In [40]:
np.random.rand(2, 2)

array([[0.60362022, 0.63368165],
       [0.51083576, 0.82694058]])

In [42]:
var1 = np.array([[1, 2], 
                 [3, 4]])
var2 = np.array([[5, 6], 
                 [7, 8]])

In [43]:
type(var1)

numpy.ndarray

In [44]:
print(var1 + var2)
print(var1 - var2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [45]:
var1 * var2

array([[ 5, 12],
       [21, 32]])

In [48]:
var1 @ var2

array([[19, 22],
       [43, 50]])

In [50]:
print(np.add(var1, var2))
print(np.subtract(var1, var2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [51]:
np.matmul(var1, var2)

array([[19, 22],
       [43, 50]])

In [52]:
np.dot(var1, var2)

array([[19, 22],
       [43, 50]])

In [57]:
np.dot([[1, 2, 3], [6, 85, 6]], [4, 5, 6])

array([ 32, 485])

In [85]:
var3 = np.random.randint(10, 100, (3, 3, 2))

In [91]:
var3

array([[[25, 96],
        [23, 74],
        [36, 10]],

       [[12, 94],
        [32, 68],
        [18, 54]],

       [[57, 67],
        [86, 56],
        [50, 84]]])

In [92]:
np.sum(var3, axis = 2)

array([[121,  97,  46],
       [106, 100,  72],
       [124, 142, 134]])

In [93]:
var1, var2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [116]:
np.stack((var1, var2), axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [117]:
np.hstack((var1, var2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [118]:
np.vstack((var1, var2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [121]:
var3.shape

(3, 3, 2)

In [138]:
var3.reshape((3, 3, 2, 1))

array([[[[25],
         [96]],

        [[23],
         [74]],

        [[36],
         [10]]],


       [[[12],
         [94]],

        [[32],
         [68]],

        [[18],
         [54]]],


       [[[57],
         [67]],

        [[86],
         [56]],

        [[50],
         [84]]]])

In [140]:
np.arange(20, 40, 3)

array([20, 23, 26, 29, 32, 35, 38])

In [141]:
np.random.randn(3, 3)

array([[-0.40768622,  1.02136527,  0.72170057],
       [ 0.30412095, -1.11543048,  0.30754428],
       [-0.47741015,  1.4820956 , -1.19054155]])

In [151]:
np.random.seed(20)
print(np.random.randn(3, 3))

[[ 0.88389311  0.19586502  0.35753652]
 [-2.34326191 -1.08483259  0.55969629]
 [ 0.93946935 -0.97848104  0.50309684]]


In [154]:
var3

array([[[25, 96],
        [23, 74],
        [36, 10]],

       [[12, 94],
        [32, 68],
        [18, 54]],

       [[57, 67],
        [86, 56],
        [50, 84]]])

In [155]:
a

array([1, 2, 3, 4, 5])

In [157]:
np.argmin(a)

0

In [158]:
np.argmax(a)

4

In [161]:
a = [1,32,3,2,4,1,2,5,45,2,14,4,56]

In [163]:
np.unique(a, return_counts = True)

(array([ 1,  2,  3,  4,  5, 14, 32, 45, 56]),
 array([2, 3, 1, 2, 1, 1, 1, 1, 1], dtype=int64))

In [164]:
var3

array([[[25, 96],
        [23, 74],
        [36, 10]],

       [[12, 94],
        [32, 68],
        [18, 54]],

       [[57, 67],
        [86, 56],
        [50, 84]]])

In [169]:
np.mean(var3, axis = -1)

array([[60.5, 48.5, 23. ],
       [53. , 50. , 36. ],
       [62. , 71. , 67. ]])