In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/bhatt/OneDrive/Desktop/whisper-main/ANN_Data/data1.csv')
label = pd.read_csv('C:/Users/bhatt/OneDrive/Desktop/whisper-main/ANN_Data/label1.csv')

In [3]:
label

3
0      2
1      2
2      3
3      3
4      3
...   ..
19994  3
19995  1
19996  2
19997  2
19998  0

[19999 rows x 1 columns]

In [4]:
data = data.values
label = label.values

In [5]:
print(data.shape, label.shape)

(19999, 20) (19999, 1)


In [6]:
np.unique(label)

array([0, 1, 2, 3, 4], dtype=int64)

In [7]:
vec_len = np.max(label) + 1

In [8]:
onehot_labels = np.eye(vec_len)[label]

In [9]:
onehot_labels.shape

(19999, 1, 5)

In [10]:
onehot_labels = onehot_labels.reshape(19999, 5)

In [11]:
onehot_labels

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [12]:
split = 0.8

trainData = data[: int(split * data.shape[0]), :]
trainlabel = onehot_labels[: int(split * label.shape[0]), :]

rem_data = data[int(split * data.shape[0]):, :]
rem_label = onehot_labels[int(split * label.shape[0]):, :]

In [13]:
print(trainData.shape, trainlabel.shape, rem_data.shape, rem_label.shape)

(15999, 20) (15999, 5) (4000, 20) (4000, 5)


In [14]:
testData = rem_data[: int(0.5 * rem_data.shape[0]), :]
testlabel = rem_label[: int(0.5 * rem_label.shape[0]), :]
validData = rem_data[int(0.5 * rem_data.shape[0]):, :]
validlabel = rem_label[int(0.5 * rem_label.shape[0]):, :]

In [15]:
print(testData.shape, validData.shape, testlabel.shape, validlabel.shape)

(2000, 20) (2000, 20) (2000, 5) (2000, 5)


In [16]:
hidden_neuron = 12

In [17]:
b1 = np.zeros(hidden_neuron)
b2 = np.zeros(5)
print(b1, b2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]


In [18]:
w1 = np.random.normal(0, 1, (20, hidden_neuron))
w2 = np.random.normal(0, 1, (hidden_neuron, 5))

In [19]:
def activation(data, choice):
    if choice == 0:
        return np.tanh(data)
    else:
        numerator = np.exp(data)
        return numerator/np.sum(numerator, axis=0)

In [20]:
alpha = 0.003

In [21]:
batch = 500

In [22]:
def cost_func(pred, label):
    return -(label * np.log(pred) + (1 - label) * np.log(1 - pred))

In [23]:
def forward_prop(data):
    a0 = data
    z1 = np.dot(a0, w1) + b1
    a1 = activation(z1, 0)
    z2 = np.dot(a1, w2) + b2
    a2 = activation(z2, 1)
    return a0, z1, a1, z2, a2

In [24]:
def accuracy(pred, label, size):
    max_data = np.argmax(pred, axis = 1)
    max_label = np.argmax(label, axis=1)
    compare = np.equal(max_data, max_label)
    return (np.sum(compare)/size)*100

In [25]:
epochs = 100

In [28]:
for epoch in range(epochs):
    for iteration in range(int(len(trainData)/batch)):
        a0,z1,a1,z2,a2=forward_prop(trainData[iteration*batch:(iteration+1)*batch,:])
        y=a2
        labelBatch=trainlabel[iteration*batch:(iteration+1)*batch,:]
        del2=(y-labelBatch)
        del1=np.dot(del2,w2.T)*(1 - a1**2)
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb1=np.sum(del1,axis=0)
        dcdb2=np.sum(del2,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b2=b2-alpha*dcdb2
        b1=b1-alpha*dcdb1
    a0,z1,a1,z2,a2=forward_prop(trainData)
    print("Training Cost",(np.sum(cost_func(a2,trainlabel)))/16000.0)
    print("Training accuracy",accuracy(a2,trainlabel,len(trainlabel)))
    
va0,vz1,va1,vz2,va2=forward_prop(validData)
vOutput=va2
accuracy = accuracy(vOutput,validlabel,2000.0)
print("validation accuracy")
print(accuracy)

Training Cost 44.87674668734429
Training accuracy 73.4920932558285
Training Cost nan
Training accuracy 74.94218388649291
Training Cost nan
Training accuracy 75.24845302831426
Training Cost nan
Training accuracy 74.65466591661979
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793


C:\Users\bhatt\AppData\Local\Temp\ipykernel_25444\1504349205.py:2: RuntimeWarning: divide by zero encountered in log
  return -(label * np.log(pred) + (1 - label) * np.log(1 - pred))
C:\Users\bhatt\AppData\Local\Temp\ipykernel_25444\1504349205.py:2: RuntimeWarning: invalid value encountered in multiply
  return -(label * np.log(pred) + (1 - label) * np.log(1 - pred))
C:\Users\bhatt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\bhatt\AppData\Local\Temp\ipykernel_25444\3942751392.py:5: RuntimeWarning: overflow encountered in exp
  numerator = np.exp(data)
C:\Users\bhatt\AppData\Local\Temp\ipykernel_25444\3942751392.py:6: RuntimeWarning: invalid value encountered in divide
  return numerator/np.sum(numerator, axis=0)


Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004687793
Training Cost nan
Training accuracy 20.0075004